# Generated by Django 5.1 on 2024-08-25 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default=datetime.datetime(2024, 8, 25, 8, 27, 24, 683994, tzinfo=datetime.timezone.utc), max_length=160, unique=True, verbose_name='slug'),
        ),
    ]
