# Generated by Django 5.1 on 2024-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='2024.08.25-08:45-gagahsahash', max_length=160, unique=True, verbose_name='slug'),
        ),
    ]
